const PAIRS=["EUR/USD","GBP/USD","USD/JPY","AUD/USD","USD/CAD","USD/CHF","NZD/USD","EUR/GBP","EUR/JPY","GBP/JPY"];
let trades=JSON.parse(localStorage.getItem("v7_trades")||"[]");
let weights=JSON.parse(localStorage.getItem("v7_weights")||"{}");
let selected=new Set(JSON.parse(localStorage.getItem("v7_pairs")||JSON.stringify(PAIRS)));
let auto=true,scanTimer=null,busy=false,filter="ALL";
const $=id=>document.getElementById(id);
$("apiKey").value=localStorage.getItem("td_key")||"";
$("threshold").addEventListener("input",()=>{$("thresholdValue").textContent=$("threshold").value});
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$("screen-"+b.dataset.screen).classList.add("active");if(b.dataset.screen==="journal")renderJournal();if(b.dataset.screen==="stats")renderStats()});
document.querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;renderJournal()});
$("scanBtn").onclick=scan;
$("connectBtn").onclick=connect;
$("disconnectBtn").onclick=disconnect;
$("autoBtn").onclick=()=>{auto=!auto;$("autoBtn").textContent="АВТОСКАН: "+(auto?"ВКЛ":"ВЫКЛ");if(auto)startTimer();else clearInterval(scanTimer)};
$("exportBtn").onclick=exportCSV;
$("clearBtn").onclick=()=>{if(confirm("Удалить весь журнал V7?")){trades=[];weights={};save();renderAll()}};
$("resetBtn").onclick=()=>{if(confirm("Сбросить API key и настройки?")){localStorage.removeItem("td_key");$("apiKey").value="";disconnect()}};
renderPairs();renderAll();

function save(){localStorage.setItem("v7_trades",JSON.stringify(trades));localStorage.setItem("v7_weights",JSON.stringify(weights));localStorage.setItem("v7_pairs",JSON.stringify([...selected]))}
function renderPairs(){$("pairs").innerHTML=PAIRS.map(p=>`<div class="pairrow"><span>${p}</span><button class="${selected.has(p)?"":"secondary"}" data-p="${p}">${selected.has(p)?"ВКЛ":"ВЫКЛ"}</button></div>`).join("");document.querySelectorAll("#pairs button").forEach(b=>b.onclick=()=>{const p=b.dataset.p;selected.has(p)?selected.delete(p):selected.add(p);save();renderPairs()})}
function ema(a,n){if(!a.length)return 0;let e=a[0],k=2/(n+1);for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,n=14){if(a.length<n+1)return 50;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){let d=a[i]-a[i-1];d>0?g+=d:l-=d}return l===0?100:100-100/(1+g/l)}
function macd(a){return ema(a,12)-ema(a,26)}
function atr(c,n=14){let x=[];for(let i=1;i<c.length;i++)x.push(Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close)));x=x.slice(-n);return x.reduce((a,b)=>a+b,0)/(x.length||1)}
function adx(c,n=14){if(c.length<n+2)return 20;let p=0,m=0,t=0;for(let i=c.length-n;i<c.length;i++){let dh=c[i].high-c[i-1].high,dl=c[i-1].low-c[i].low;p+=dh>dl&&dh>0?dh:0;m+=dl>dh&&dl>0?dl:0;t+=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close))}let P=p/t*100,M=m/t*100;return 100*Math.abs(P-M)/Math.max(1,P+M)}
function analyze(c,pair){const a=c.map(x=>x.close),last=c.at(-1),prev=c.at(-2),e9=ema(a,9),e21=ema(a,21),e50=ema(a,50),R=rsi(a),M=macd(a),A=adx(c);const mean=a.slice(-20).reduce((x,y)=>x+y,0)/Math.min(20,a.length);const sd=Math.sqrt(a.slice(-20).reduce((x,y)=>x+(y-mean)**2,0)/Math.min(20,a.length));const upBand=mean+2*sd,lowBand=mean-2*sd;let parts={EMA:e9>e21?15:-15,TREND:e21>e50?15:-15,RSI:R>=52&&R<=70?10:R<=48&&R>=30?-10:0,MACD:M>0?15:-15,ADX:A>=25?(e9>e21?12:-12):0,BOLL:last.close<lowBand?8:last.close>upBand?-8:0};const recent=c.slice(-10);const sup=Math.min(...recent.map(x=>x.low)),res=Math.max(...recent.map(x=>x.high));parts.LEVEL=last.close<=sup*1.0015?8:last.close>=res*.9985?-8:0;parts.CANDLE=last.close>last.open&&last.close>prev.close?10:last.close<last.open&&last.close<prev.close?-10:0;let pos=Object.values(parts).filter(x=>x>0).reduce((a,b)=>a+b,0),neg=-Object.values(parts).filter(x=>x<0).reduce((a,b)=>a+b,0);let direction=pos>=neg?"CALL":"PUT",base=Math.round(Math.max(pos,neg)),st=weights[pair]||{win:0,loss:0},n=st.win+st.loss,emp=n>=10?st.win/n:.5,score=Math.min(97,Math.max(0,Math.round(base*.8+emp*20)));return{pair,direction,score,parts,rsi:R,macd:M,adx:A,entry:last.close}}
async function candles(pair){const key=localStorage.getItem("td_key");const tf=$("timeframe").value;if(!key)throw Error("Нет API key");const u=`https://api.twelvedata.com/time_series?symbol=${encodeURIComponent(pair)}&interval=${tf}&outputsize=120&apikey=${encodeURIComponent(key)}`;const j=await (await fetch(u)).json();if(!j.values)throw Error(j.message||"Нет данных");return j.values.reverse().map(x=>({open:+x.open,high:+x.high,low:+x.low,close:+x.close,time:x.datetime}))}
async function price(pair){const key=localStorage.getItem("td_key");const u=`https://api.twelvedata.com/price?symbol=${encodeURIComponent(pair)}&apikey=${encodeURIComponent(key)}`;const j=await(await fetch(u)).json();if(!j.price)throw Error(j.message||"Нет цены");return +j.price}
async function scan(){if(busy)return;if(!localStorage.getItem("td_key"))return alert("Введите API key Twelve Data");if(!selected.size)return alert("Выберите хотя бы одну пару");busy=true;$("status").textContent="● SCANNING";$("status").className="pill";let results=[];for(const p of selected){try{results.push(analyze(await candles(p),p))}catch(e){results.push({pair:p,error:e.message})}}results.sort((a,b)=>(b.score||0)-(a.score||0));$("ranking").innerHTML=results.map(x=>x.error?`<div class="pairrow"><span>${x.pair}</span><span class="badge loss">ERROR</span></div>`:`<div class="pairrow"><span>${x.pair} · ${x.direction}</span><span class="badge ${x.score>=+$("threshold").value?"win":"neutral"}">${x.score}/100</span></div>`).join("");const best=results.find(x=>!x.error&&x.score>=+$("threshold").value);if(best){show(best);createTrade(best)}else{show(null)}$("status").textContent="● LIVE";$("status").className="pill ok";busy=false}
function show(a){if(!a){$("pair").textContent="НЕТ СИГНАЛА";$("direction").textContent="NO TRADE";$("direction").className="direction";$("score").textContent="—";$("reason").textContent="Нет пары выше заданного порога.";$("indicators").innerHTML="";return}$("pair").textContent=a.pair;$("direction").textContent=a.direction==="CALL"?"CALL ↑":"PUT ↓";$("direction").className="direction "+(a.direction==="PUT"?"put":"");$("score").textContent=a.score+"/100";$("reason").textContent=`RSI ${a.rsi.toFixed(1)} · MACD ${a.macd>=0?"↑":"↓"} · ADX ${a.adx.toFixed(1)} · EMA/уровни/свеча учтены`;$("indicators").innerHTML=Object.entries(a.parts).map(([k,v])=>`<div class="indicator"><b>${k} ${v>0?"✓":v<0?"↓":"—"}</b><span>${v>0?"подтверждает":"нейтрально/против"}</span></div>`).join("")}
async function createTrade(a){let recent=trades.find(t=>t.result==="OPEN"&&t.pair===a.pair&&Date.now()-t.createdAt<10000);if(recent)return;let entry=a.entry;try{entry=await price(a.pair)}catch{}const now=Date.now(),expiry=now+(+$("expiry").value*1000);const t={id:now,pair:a.pair,direction:a.direction,score:a.score,createdAt:now,expiryAt:expiry,entryPrice:entry,exitPrice:null,result:"OPEN",timeframe:$("timeframe").value,indicators:a.parts};trades.unshift(t);trades=trades.slice(0,2000);save();renderAll();setTimeout(()=>settle(t.id),Math.max(500,expiry-Date.now()))}
async function settle(id){const t=trades.find(x=>x.id===id);if(!t||t.result!=="OPEN")return;try{t.exitPrice=await price(t.pair)}catch(e){t.result="UNKNOWN";save();renderAll();return}t.closedAt=Date.now();if(t.direction==="CALL")t.result=t.exitPrice>t.entryPrice?"WIN":t.exitPrice<t.entryPrice?"LOSS":"DRAW";else t.result=t.exitPrice<t.entryPrice?"WIN":t.exitPrice>t.entryPrice?"LOSS":"DRAW";if(t.result==="WIN"||t.result==="LOSS"){weights[t.pair]=weights[t.pair]||{win:0,loss:0};weights[t.pair][t.result==="WIN"?"win":"loss"]++}save();renderAll()}
function renderJournal(){const arr=filter==="ALL"?trades:trades.filter(t=>t.result===filter);$("journal").innerHTML=arr.length?arr.map(t=>`<tr><td>${new Date(t.createdAt).toLocaleTimeString("ru-RU")}</td><td>${t.pair}<br>${t.timeframe}</td><td><span class="badge ${t.direction==="CALL"?"win":"loss"}">${t.direction}</span></td><td>${t.score}</td><td>${fmt(t.entryPrice)}</td><td>${fmt(t.exitPrice)}</td><td><span class="badge ${t.result.toLowerCase()}">${t.result}</span></td></tr>`).join(""):`<tr><td colspan="7">Нет записей</td></tr>`}
function renderAll(){const w=trades.filter(t=>t.result==="WIN").length,l=trades.filter(t=>t.result==="LOSS").length,o=trades.filter(t=>t.result==="OPEN").length;$("total").textContent=trades.length;$("open").textContent=o;$("wins").textContent=w;$("losses").textContent=l;$("rate").textContent=(w+l?((w/(w+l))*100).toFixed(1):"0")+"%";renderJournal()}
function renderStats(){let rows=PAIRS.map(p=>{let a=trades.filter(t=>t.pair===p&&(t.result==="WIN"||t.result==="LOSS")),w=a.filter(t=>t.result==="WIN").length;return`<div class="pairrow"><span>${p}<br><small>${a.length} закрытых</small></span><span class="badge ${a.length&&w/a.length>=.75?"win":a.length?"loss":"neutral"}">${a.length?(w/a.length*100).toFixed(1):0}%</span></div>`}).join("");$("pairStats").innerHTML=rows;let ranges=[[60,69],[70,79],[80,89],[90,100]];$("scoreStats").innerHTML=ranges.map(r=>{let a=trades.filter(t=>t.score>=r[0]&&t.score<=r[1]&&(t.result==="WIN"||t.result==="LOSS")),w=a.filter(t=>t.result==="WIN").length;return`<div class="pairrow"><span>Score ${r[0]}–${r[1]}</span><b>${a.length?(w/a.length*100).toFixed(1):0}% · ${a.length}</b></div>`}).join("")}
function fmt(v){return v==null?"—":Number(v).toFixed(6)}
function exportCSV(){const h=["id","time","pair","timeframe","direction","score","entryPrice","exitPrice","result","createdAt","expiryAt","closedAt"];const rows=trades.map(t=>h.map(k=>JSON.stringify(k==="time"?new Date(t.createdAt).toISOString():(t[k]??""))).join(","));const blob=new Blob([[h.join(","),...rows].join("\n")],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="pocket-signal-v7-journal.csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function connect(){const k=$("apiKey").value.trim();if(!k)return alert("Введите API key");localStorage.setItem("td_key",k);$("status").textContent="● CONNECTING";scan();startTimer()}
function disconnect(){clearInterval(scanTimer);$("status").textContent="● OFFLINE";$("status").className="pill"}
function startTimer(){clearInterval(scanTimer);scanTimer=setInterval(()=>{if(auto)scan()},60000)}
